### ISSUE TITLE
Getting 'Could not validate this request.' with Client Calls

### ISSUE THREAD

**Issue by tjlytle** [twilio/OpenVBX#210]
Just updated to 1.2.9 and get the 'Could not validate this request. Goodbye.' message trying to dial out using the Twilio Client (but not one of the other devices). I'm digging into the code, just thought this might ring a bell.

**Comment by unclespode** [comment]
I was having this issue and then I went to the settings page and it suggsted I needed to press the "update" button to update something (it was in a yellow box) and now the problem has gone away.
