### ISSUE TITLE
Error connecting to Twilio "SSL certificate problem: unable to get local issuer certificate (0)"

### ISSUE THREAD

**Issue by johndpalm** [twilio/OpenVBX#252]
I forked the GitHub OpenVBX project, created an Azure Web Site (with MySQL on ClearDb), and configured it to pull from the fork. (Steps to reproduce are similar to:  http://www.windowsazure.com/en-us/develop/php/common-tasks/create-a-php-web-site) 

The site comes up and I'm able to configure it until it tries to connect to Twilio.

On the Connect to Twilio page, after entering the required fields, I get this error:

SSL certificate problem: unable to get local issuer certificate (0)

I suspect this is something on the Azure side since I've seen posts with the same "unable to get local issuer certificate" message (but no resolution).

There is no errors in the web server logs or in my Twilio account logs.

The error doesn't give enough details about what it is doing to diagnose the issue.

I created a StackOverflow question as well: http://stackoverflow.com/questions/19574572/azure-web-sites-error-connecting-to-twilio-ssl-certificate-pro-blem-unable-to

**Comment by hero789** [comment]
hello , 

where is the file "\config\config.php" ?

**Comment by tofu713** [comment]
~/wwwroot/OpenVBX/config/config.php

**Comment by waiz3ple** [comment]
it not working pls who has the solution
