### ISSUE TITLE
Online Phone/Calls Do Not Work with Safari

### ISSUE THREAD

**Issue by ZacharyDuBois** [twilio/OpenVBX#283]
When using the online phone to call, it does not work on Safari for Mac. I am currently on DP2 of 10.10 so, I am unsure if it is just because of that. Chrome and Firefox seem fine.

**Comment by kaburkett** [comment]
I discovered the reason it doesnt place the call is because it is waiting on permission to use the microphone on the pc. You need to enable safari use of the microphone somehow (or enable popup)

**Comment by ZacharyDuBois** [comment]
I've moved off of this onto something custom. This was too buggy to use.
