### ISSUE TITLE
Way to change user login session timeout

### ISSUE THREAD

**Issue by JamesReate** [twilio/OpenVBX#287]
Hi,
This is a feature request: Add a user setting from the web ui to be able to set the user login session timeout. 
Currently the session timeout logs the user out after a couple hours or so, and there is no way to increase or decrease it without mucking with a bunch of PHP code (at least not that I've seen).

**Comment by Gipetto** [comment]
This has been here a long time.

You can edit the session time out in `OpenVBX/config/config.php` in the Session configuration block. Change the `$config['sess_expiration']` parameter to what you want it to be.
