### ISSUE TITLE
Download version 1.2.5 after install shows OpenVBX • v1.2.14 r79 also showing There is a newer version of OpenVBX available: Version 1.2.15. message in settings

### ISSUE THREAD

**Issue by ronsmart** [twilio/OpenVBX#305]
Download version 1.2.5 after install shows OpenVBX • v1.2.14 r79 also showing There is a newer version of OpenVBX available: Version 1.2.15. message in settings

**Comment by opheliadesign** [comment]
Same issue here

**Comment by Gipetto** [comment]
Where are you downloading OpenVBX from?

**Comment by opheliadesign** [comment]
The OpenVBX website 

Benjamin McMahan
CEO, Lead Developer
Ophelia Design

**Comment by Gipetto** [comment]
Ah, looks like the version number is wrong in the code (forgot to bump when releasing 1.2.15). I'll fix.

**Comment by opheliadesign** [comment]
Thanks! 

Benjamin McMahan
CEO, Lead Developer
Ophelia Design

**Comment by Gipetto** [comment]
Okay, I've fixed in master and the zip & tarballs are good.
You don't need to download and install the update, you can just edit:

`OpenVBX/config/version.php` and change the version number to from `1.2.14` to `1.2.15`

**Comment by opheliadesign** [comment]
Perfect, don't know how I missed that file - was trying to fix it myself 

Benjamin McMahan
CEO, Lead Developer
Ophelia Design

**Comment by Gipetto** [comment]
This is long since fixed. Closing.

**Comment by ronsmart** [comment]
Thank you @Gipetto
