### ISSUE TITLE
[Critical] Play button doesn't work

### ISSUE THREAD

**Issue by afilina** [twilio/OpenVBX#311]
I click the button to play a voice message and it doesn't work. Nothing happens.
Works for my partner on a Linux, but not on any Mac browser (tried Safari, Chrome and Firefox).

It used to work on my Mac too, but that was over a year ago.

**Comment by Gipetto** [comment]
I can't replicate this. Is this still happening? Is there console output from the browser that may help?

**Comment by afilina** [comment]
v1.2.15 r79

Uncaught TypeError: Message.Player.currentSoundObject.stop is not a function

_togglePlayForMessage @ ?g=js&v=1024:568
(anonymous function) @ ?g=js&v=1024:568
Message.Player.getRecordingUrls @ ?g=js&v=1024:563
Message.Player.togglePlayForMessage @ ?g=js&v=1024:568
(anonymous function) @ ?g=js&v=1024:576
f.event.handle @ ?g=js&v=1024:297
i.handle.k @ ?g=js&v=1024:297

**Comment by dstockto** [comment]
@afilina Do you have flash disabled by default (need to ctrl-click to run flash stuff)? I had that and couldn't get the play button to work either. When I re-enabled flash ( :disappointed: ) then the play button worked for me.

**Comment by Gipetto** [comment]
I think that I figured this one out. OpenVBX gets a messageId => voicemailUrl map via a javascript load and this script was being cached by the browser. So while the UI would notice that the voicemail was there the script would still have an empty map. 

This is not one of the best designed things in OpenVBX, but I've implemented a couple of cache-busting features (an HTTP way and a less traditional, but more cross browser effective url timestamp method) to ensure that this script loads fresh every time: https://github.com/twilio/OpenVBX/commit/464c0d34d168368baa0ad0f03456786c8857367c

Its currently in the develop branch only. It'll go out in the next release.

**Comment by Gipetto** [comment]
This shipped with 1.2.18. Closing.

**Comment by maxclicks** [comment]
Not to dig up a closed thread.  I am on 1.2.20 and still having the same issue.  Any idea what I can do to fix it?

Thanks for any help

**Comment by stuboo** [comment]
Same as @maxclicks

**Comment by tripflex** [comment]
I'm also having this issue on latest release, and made sure all cache was cleared

**Comment by tripflex** [comment]
For anybody having this issue, I was able to resolve this by updating the soundmanager library files, see #402 for more details
