### ISSUE TITLE
Voice option "Alice" does not work.

### ISSUE THREAD

**Issue by cimesport** [twilio/OpenVBX#313]
In Settings>System config, the voice option "Alice" does not work. If you set Alice, and a language option, you always get a default Man US voice. I believe this is because in /OpenVBX/views/settings/site-system-config.php, line 174, the voice languages are set from the dropdown thus

						$options = array(
							'en-GB' => 'British English',
							'en' => 'English',
							'fr' => 'French',
							'de' => 'German',
							'it' => 'Italian',
							'es' => 'Spanish',

which is correct for Voice='Man' or Voice='Woman', but Alice requires different Language values, so 
the code would need to look like this

						$options = array(
							'en-GB' => 'British English',
							'en-US' => 'English',
							'fr-FR' => 'French',
							'de-DE' => 'German',
							'it-IT' => 'Italian',
							'es-ES' => 'Spanish',

Not sure how you would run a dynamic check on the Voice attribute to change the language dropdown, or I would have posted it.

**Comment by Gipetto** [comment]
Mmm... yeah. Crap. This'll need a UI Settings change to present a different dropdown when using Alice.

**Comment by Gipetto** [comment]
I just pushed a change to the develop branch that fixes this issue. Now the setting screen will swap out language options based on the voice.

Can you possibly do an extra test before release?

**Comment by Gipetto** [comment]
Fixed in 1.2.17
