### ISSUE TITLE
New Plugin Submission: OpenVBX-Plugin-cURL

### ISSUE THREAD

**Issue by cxevan7** [twilio/OpenVBX#315]
Plugin Name: OpenVBX-Plugin-cURL
Plugin Url: https://github.com/cxevan7/OpenVBX-Plugin-cURL
Plugin Description: Allows you to add an applet that makes cURL requests and parses those requests to give a response back to the caller. Modified version of another applet by Jonathan Kressaty <jonathan.kressaty@gmail.com>

**Comment by Gipetto** [comment]
Sorry to have missed this. It has been added to the plugins list.
Thanks!
