### ISSUE TITLE
browser phone dont work

### ISSUE THREAD

**Issue by rockdrigo** [twilio/OpenVBX#317]
after create a flow and put my status online, i cant make that browserphne works, y was tried with many browsers, and all the time, i recieve the veoicemail record

**Comment by taropaa** [comment]
It may be a permissions problem with your server. Had the same problem until I chmod'ed everything to 775 and made sure the group was apache (or whatever the server is).
Also make sure you uncomment the .htaccess.

**Comment by kaburkett** [comment]
So this issue actually could be because you didnt enter the application SID... so if you go to settings and then Twilio Account- make sure Twilio Client Application SID is filled in.

**Comment by Gipetto** [comment]
There's currently a bug in the installation script that prevents the population of the Application Sid. The Application is created but the Sid is not saved.

This is working in the develop branch and will be corrected in the next release.
