### ISSUE TITLE
New Plugin Submission: Save and Reply

### ISSUE THREAD

**Issue by matthewgall** [twilio/OpenVBX#318]
Plugin Name: Save and Reply
Plugin Url: https://github.com/matthewgall/openvbx-saveandreply
Plugin Description: openvbx-saveandreply is a plugin for OpenVBX (http://openvbx.org) that allows you to save an incoming SMS to an inbox and automatically respond with an acknowledgement.

**Comment by Gipetto** [comment]
Added. Thank you!
http://www.openvbx.org/plugins/
