### ISSUE TITLE
Empty Twimls

### ISSUE THREAD

**Issue by ronnieserr** [twilio/OpenVBX#319]
A new installation of OpenVbx. Calling voice and sms returns "unknown error." When in flows, clicking View Twiml returns a blank page. 

11200 HTTP retrieval failure

An attempt to retrieve content from http://calliflow.com/openvbx/index.php/twiml/start/voice/1 returned the HTTP status code 500.

Any idea what could be going on?

**Comment by karlfi** [comment]
I have the same problems. This occur when I put the project on a hosting site.

**Comment by kaburkett** [comment]
Try going to Settings->Twilio Account (Make sure all info is accurate)->Update.. Does that fix it?

**Comment by ronnieserr** [comment]
Thanks -- the problem was .htaccess setting when openvbx is not installed on the host's root.
