### ISSUE TITLE
Can't save a new flow, i'm getting a 406 error

### ISSUE THREAD

**Issue by infadm** [twilio/OpenVBX#324]
![screen shot 2015-06-14 at 10 43 32 am](https://cloud.githubusercontent.com/assets/12877673/8146545/4bf4f166-1282-11e5-9589-d8f73f111205.png)

**Comment by Gipetto** [comment]
That is very odd. 406 is basically the server responding to the client that while the operation completed it cannot respond appropriately based on the supplied Accept headers in the request. 

Did the flow actually save?

**Comment by infadm** [comment]
I think is something to do with php version.

**Comment by Gipetto** [comment]
Can you elaborate here when you get the issue locked down? I'm curious as to what the answer is and if there's a way to safeguard against this.
