### ISSUE TITLE
First Login connectAuthTenant() Error

### ISSUE THREAD

**Issue by JeremyCee** [twilio/OpenVBX#325]
Had a very choppy install experience. 

Now that I FINALLY got to successful install, I'm getting this same issue that appears to be ignored in the support forum: https://getsatisfaction.com/openvbx/topics/first-login-gives-php-error
 
>>><<<

After the installation is success, I try logging in and i receive the following PHP error 

A PHP Error was encountered 

Severity: 8192 

Message: Non-static method OpenVBX::connectAuthTenant() should not be called statically, assuming $this from incompatible context 

Filename: auth/login.php 

Line Number: 104

**Comment by Gipetto** [comment]
Seems that method can just be made static. That's the only usage and it appears to be used as intended.

**Comment by mimecine** [comment]
Tried changing to static and login now works.

**Comment by JeremyCee** [comment]
Any guidance on HOW I can make it "static"? I can pick through/read code but have no idea what it's doing.

**Comment by JeremyCee** [comment]
@Gipetto & @mimecine == I APPRECIATE you jumping in to answer!!

**Comment by Gipetto** [comment]
Yep: https://github.com/twilio/OpenVBX/commit/69addfd9747659d25bc76d2496f60a2c3f96d677

**Comment by JeremyCee** [comment]
This is the first time I've ever posted to GitHub ... kudos to you for making it a VERY satisfying experience!! I'll check back in and close this issue when I have a chance to test it this weekend!

**Comment by Gipetto** [comment]
Fixed in 1.2.17

**Comment by edwingeo** [comment]
Instead of $connect_auth = OpenVBX::connectAuthTenant($user->tenant_id);
use below code
$obj = new OpenVBX();
$connect_auth = $obj->connectAuthTenant($user->tenant_id);
Then it will get works...Rocksssssss
