### ISSUE TITLE
Incoming SMS doesn't work.

### ISSUE THREAD

**Issue by stpete** [twilio/OpenVBX#326]
Hey guys,

I can send (Twilio logs the inbound and outbound messages) but nothing is received back through OpenVBX. I'm hosoted on hostgator.

How to fix it?

Thanks
ST

**Comment by Gipetto** [comment]
To receive SMS on OpenVBX a flow must be set up to handle incoming SMS. Create an SMS Flow on the number you'd like to receive SMS on and use the SMS Inbox applet to save the SMS to the appropriate inbox.

**Comment by stpete** [comment]
I created flow SMS Flow
![scrn vbx](https://cloud.githubusercontent.com/assets/13082622/8439535/b669663e-1f3a-11e5-8c9e-1e0c0500d647.jpg)

How do I use "SMS Inbox applet" to save SMS? Is it preinstalled?

![scrn vbx 1](https://cloud.githubusercontent.com/assets/13082622/8439615/2ef81668-1f3b-11e5-88bc-60c3468207d0.jpg)

**Comment by Gipetto** [comment]
The SMS Inbox applet is configured in the flow setup. You can have incoming SMS messages assigned to either a user or a group's inbox.

When you dropped the SMS Inbox applet on to the flow editor it should have presented you with a new pane where the inbox could be selected.

**Comment by stpete** [comment]
It' s working now. Thank you very much!
