### ISSUE TITLE
Using the web based number pad while on a call doesn't work

### ISSUE THREAD

**Issue by cromulus** [twilio/OpenVBX#327]
Calling a number with an IVR doesn't seem to work with the web based number pad.

**Comment by Gipetto** [comment]
I can't replicate this. I was able to successfully navigate an IVR using a client call and number pad.

**Comment by Gipetto** [comment]
I also can't find anything that would indicate that OpenVBX is "doing it wrong". I wouldn't doubt that there are edge cases where Twilio Client may not be compatible with 100% of the IVR systems out there. I would contact `help@twilio.com` to see if you can get a more in depth answer about possible incompatibilities with Twilio Client (which powers the OpenVBX browser phone) and some IVR systems.
