### ISSUE TITLE
web ui to call a number from a device

### ISSUE THREAD

**Issue by cromulus** [twilio/OpenVBX#328]
I have a device in a conference room and I'm trying to call an outside number with the conference room phone: I use the web UI to select the device and the caller ID number. I then enter the telephone number I wish to call using the device. The device rings, but when I pick up, I hear: "Could not validate this request"

The twilio log shows an outgoing call from my callerID number to the device number lasting 4 seconds. 

But that's it. No log of any call going to the outside number at all. My apache logs show a post request to twiml/dial with the right callerid and "to" number. However, trying to replicate that request results in the TWIML response:

```
<Response>
<Say voice="alice" language="en">Could not validate this request. Goodbye.</Say>
<Hangup/>
</Response>
```

Any ideas? this is sort of a make or break feature for us....

**Comment by unclespode** [comment]
I'm having the same problem and can't resolve.

**Comment by Gipetto** [comment]
I think I finally have this one figured out (its been out there a long time). There's a bug in how the request validation routine uses `parse_str` when **not** running mod-rewrite support in Apache.

Here is the fix. If one or both of you could test that'd be wonderful: https://github.com/twilio/OpenVBX/commit/53a4ffb120da9a0465ea296f4450c6a04d5b0a9a

**Comment by unclespode** [comment]
Mine was happening even with mod_rewrite on and I've fixed it whilst solving me other issues. If cromulus is still having issues, he could give it a go.

**Comment by Gipetto** [comment]
How did you fix your issue? We should see if your fix can be made permanent.

**Comment by unclespode** [comment]
In the Twilio Account tab in settings, it was in a yellow box suggesting I needed to press "update" to save in a new way. Once I did this, the requests went through fine. A little odd - why couldn't that have been done when I upgraded?

**Comment by Gipetto** [comment]
Ah, yeah... that's the side effect of a PREVIOUS bug where that application sid wouldn't be saved during install. That recently got fixed. 

Maybe that should be something that gets rectified during upgrade.

**Comment by unclespode** [comment]
Probably a little late to bother writing code for that - but just having a notification in an FAQ response or something.

**Comment by Gipetto** [comment]
It doesn't look like @cromulus is coming back. I'm gonna go ahead and close this issue. One of these two solutions should fix him up. 

My fix (https://github.com/twilio/OpenVBX/commit/53a4ffb120da9a0465ea296f4450c6a04d5b0a9a) will be out with the next release.
