### ISSUE TITLE
Can't update due to redirect loop

### ISSUE THREAD

**Issue by unclespode** [twilio/OpenVBX#332]
I'm on version 1.2.16 trying to upgrade. I have mod_rewrite enabled. I have tried with both on and off, whenever I switch to the new version, I get a redirect loop, going back and forth from index.php to index.php/install

I have edited the database directly to turn off mod_rewrite and it makes no difference.

I am on a very standard Ubuntu Server install with Apache and PHP. The only error I can see, is on my about page:

Client Application:
  - An error occurred when requesting the Client Application data:

I'm not sure if this is relevant. I'm desperate to upgrade it as I'm currently having a lot of problems - for example, not being able to make phone calls from the browser.

**Comment by unclespode** [comment]
It seems when I mis-read the instructions. I copied config.php and database.php but NOT openvbx.php

However, it would make sense if there was a check for this, instead I was given a redirect loop.

**Comment by Gipetto** [comment]
I figured that's what was going on there. Agreed that it could be much better.

**Comment by unclespode** [comment]
Well hopefully the next person with this issue will find my post!
