### ISSUE TITLE
iPhone App Reply To Text Hangs

### ISSUE THREAD

**Issue by gevansweb** [twilio/OpenVBX#333]
Whenever I try to reply to a text message using the OpenVBX iPhone app on my iPhone 5S with the latest iOS 8.4, the application hangs forever. No other buttons are usable. The only way out, is to press the home button and to close the application and restart it.

Same thing happens when I attempt to make a phone call and click on the phone icon at the bottom right.

**Comment by Gipetto** [comment]
Unfortunately the iPhone app has been long since abandoned. We need to find out who has the app store credentials so that we can get it de-listed. We have no way to support it any more.
