### ISSUE TITLE
Feature Request: Per User Dial Out Numbers

### ISSUE THREAD

**Issue by unclespode** [twilio/OpenVBX#335]
When users dial out they can pick their outgoing number. It would be good to be able to restrict this list on a per user basis. For example, I wouldn't want our sales people dialing out on the technical support line, for example.

**Comment by Gipetto** [comment]
Yeah, this crossed my mind a long time ago when I saw a list of 200 phone numbers just be unusable. Unfortunately there's no active time to support new features in OpenVBX. I fix up bugs when I can, but don't have any time for new features.

**Comment by Gipetto** [comment]
Pull requests will be considered, though.

**Comment by unclespode** [comment]
What is the general state of the project then? Basically just to bug fix what is there? I thought Twilio was supposed to be actively developing it?

**Comment by Gipetto** [comment]
OpenVBX is in maintenance mode. There is no feature development going on. Admittedly, this should be made more clear.
