### ISSUE TITLE
Feature Request: Change Call Announcement Text

### ISSUE THREAD

**Issue by unclespode** [twilio/OpenVBX#336]
Currently, this is the line in twiml.php:

$gather->say("This is a call for {$name}. To accept, Press 1.", $this->say_params);

I think this should be a setting that administrators can change, as my staff are confused when they get this message and don't accept the call thinking it's a scam.

**Comment by Gipetto** [comment]
This would be nice. Unfortunately there's no active time to support new features in OpenVBX. I fix up bugs when I can, but don't have any time for new features.

**Comment by Gipetto** [comment]
Pull requests will be considered, though.
