### ISSUE TITLE
Openvbx install error

### ISSUE THREAD

**Issue by friendlytf** [twilio/OpenVBX#340]
3.Connect to Twilio
Login to your dashboard for your Twilio SID and Token.

To set up a Twilio Connect Application for this install visit your Account’s Connect Applications Section and create an Application.

Twilio SID 
ACc91766cfc8214766ae9139c7435d2505
Twilio Token 
••••••••••••••••••••••••••••••••

Twilio Connect Sid (optional) 

(((come up with this error below))

Protocol "https" not supported or disabled in libcurl (0)

**Comment by Gipetto** [comment]
libcurl is part of your server configuration, not OpenVBX. A quick search of the libcurl documentation found:

> **3.21 Protocol xxx not supported or disabled in libcurl**
>
> When passing on a URL to curl to use, it may respond that the particular protocol is not supported or disabled. The particular way this error message is phrased is because curl doesn't make a distinction internally of whether a particular protocol is not supported (i.e. never got any code added that knows how to speak that protocol) or if it was explicitly disabled. curl can be built to only support a given set of protocols, and the rest would then be disabled or not supported.

You should contact your server administrator or web host to see if they can look in to the curl configuration on your server.
