### ISSUE TITLE
New Plugin Submission: SMS Conversation View

### ISSUE THREAD

**Issue by jpwalters** [twilio/OpenVBX#350]
Plugin Name: SMS Conversation View
Plugin Url: https://github.com/jpwalters/OpenVBX-Plugin-SMS-Conversation
Plugin Description: This plugin will group sms conversations into a single list and when selected it will show the sms conversation thread in an instant messenger like view.

**Comment by nistala** [comment]
+1, I've been using this and it works great!

**Comment by Gipetto** [comment]
Done. Sorry this took a while to get around to.

**Comment by gegere** [comment]
@Gipetto I believe there is an bug / mistake with the .mp3 file location within the repo. This mp3 is played when texts are received. I moved all the contents to the root directory to help with the installation if someone is using `git clone` or `git submodules`.

I issued a pull request to @jpwalters thinking he might be open to making the plugin easier to install.

If you would like me to use a pull request to your repo fork, please let me know.

**Comment by jpwalters** [comment]
@gegere thanks the heads up.  I've corrected the issue and updated the project.  In order to install the plugin all you have to do is put the entire "sms-conversation" folder into the plugins folder.  You can review this commit for more details (https://github.com/jpwalters/OpenVBX-Plugin-SMS-Conversation/commit/34d85354855e64b8f4b70ef10ab71e9250b804cf).  Thanks again.
