### ISSUE TITLE
No Text Messages In Inbox

### ISSUE THREAD

**Issue by wm820** [twilio/OpenVBX#353]
I do not receive Text Messages in my OpenVBX Inbox.  I am receiving the forwarded text messages to my iPhone as I created in the SMS Flow.

**Comment by liquidia** [comment]
Same issue i am using nginx server

**Comment by dc500** [comment]
Updated and now I have the same problem. It works and then stops. Then works again.

**Comment by gegere** [comment]
The "deleted" message has been a continued issue for my installation.  Striping out all the plugins and the situation has left me scratching my head.

SMS from +19513042294

Message:

deleted

**Comment by dc500** [comment]
@gegere  I believe that means a MMS (picture message.) At least, that's the case for me.

**Comment by gegere** [comment]
I send a text from a Google Voice number to test and I can reproduce it, "deleted". Also, sending a text via another twilio number via OpenVBX reproduces that issue also, "deleted.

More info, it seems to be whenever I have a SMS flow with a auto response to a inbound text that this "deleted" msg in the inbox occurs. I am not able to see what the original incoming text was.

**Comment by dc500** [comment]
My problem is SOLVED. Don't know how or why it happened, but my "flow was switched." I didn't do it.
How did I figure this out. I looked over the logs. It read:

```
<Response>
    <Say voice="woman" language="en">Error 4-oh-4 - Flow not found.</Say>
</Response>
```

 LOL.

@gegere I think it may have something to do with expired cookies. I'm not 100% sure. Did you contact Twilio about this issue? What are your logs saying? Any error codes?

**Comment by mfkp** [comment]
@gegere just ran into the same problem.

For the record: MMS has never been suported, and will result in `deleted`.

Text messages work if the only action in a flow is sending to the SMS inbox.

If you add a "reply" action, then try to send it to the SMS inbox, it will result in `deleted`. When looking at the TwiML that gets generated, I assume it's because it redirects without the message data, resulting in an blank message.

I'm looking into how easy it would be to redirect with the message parameters.

**Comment by mfkp** [comment]
Nevermind, that wasn't the issue. It's a problem with cookies in more recent versions of PHP.

Discussion and workaround here: https://github.com/twilio/OpenVBX/issues/341

**Comment by gegere** [comment]
@mfkp nice job. What PHP version are you using?

**Comment by mfkp** [comment]
PHP 5.5.9-1ubuntu4.7

**Comment by gegere** [comment]
The version I am running is PHP 5.5.9-1ubuntu4.20. 

Are you knowledgeable with Docker containers? 
https://github.com/htmlgraphic/Apache

I have been working on build processes to test OpenVBX deployments. The repo I shared with you contains a branch called Envoyer to test PHP 7 and move this update forward correctly.

**Comment by mfkp** [comment]
Ah interesting. I've played around with Docker but it hasn't really stuck for me. I do most of my development using Vagrant and VirtualBox, then just do traditional deployments to an identical infrastructure in production.

It could be nice to have a Docker image for easily testing/deploying/updating OpenVBX, similar to how Metabase does it: http://www.metabase.com/start/docker

Although I've been burned by that in the past when my docker instance stopped responding for no discernible reason. I never actually figured out what was wrong, just redeployed it without docker.

**Comment by gegere** [comment]
I have been building this for about 2 years. Please send me an email. I would be open to show you many advantages. There is a reason why a process stopped, the nice thing about orchestration tools is that the system will start up again within seconds. Unlike Vagrant systems complexity is reduced, there is a learning curve but after that more time can be spent actually writing code.
