### ISSUE TITLE
CentoOS on GCE Installation Fails At Step 5

### ISSUE THREAD

**Issue by kmontenegro** [twilio/OpenVBX#359]
I checked[ this issue](https://github.com/twilio/OpenVBX/issues/304), which was closed, and used IE w/o a LastPass plug-in as well as Iceweasel w/o LastPass and am still hung up on step 5 of the install.

Is there a way to manually commit the values from the installation routine?

Environment is CentOS on Google Compute Engine. Looked at all the permissions & mod_rewrite is enabled.

**Comment by Gipetto** [comment]
I wonder if this is related to https://github.com/twilio/OpenVBX/issues/360

**Comment by kmontenegro** [comment]
Yes, suggested edit let me complete the install. Thanks!
