### ISSUE TITLE
PHP errors in my OpenVBX installation

### ISSUE THREAD

**Issue by PepperKev** [twilio/OpenVBX#403]
Hello,
I just noticed that my OpenVBX installation isn't working, when I phone the number I get "Unknown error" and when I try to log into the OpenVBX web interface, I get a long list of errors. 
They all say:

>  A PHP Error was encountered
> Severity: 8192
> Message: Methods with the same name as their class will not be constructors in a future version of PHP; CI_Hooks has a deprecated constructor
> Filename: libraries/Hooks.php
> Line Number: 30

Except with different filenames and line numbers. 
So I can't even log in and my clients can't reach me. I'm not sure how to fix this, and I'm not a programmer; my skill set is installing the package, not debugging it. 
So on that note, will it make things worse if I just reinstall the package or is there something I can do as a rank amateur to just fix it?

**Comment by andresleecom** [comment]
Hi there.

I suggest to install a fresh one.

Please paste screenshots of the errors.

**Comment by PepperKev** [comment]
Thanks Andre
I tried that and ran into MySQL errors. 
In the end, the fix was for my hosting provider to roll back my account to PHP version 5.6 (from PHP7) and that resolved everything: the PHP errors, the inability of the new installation package to find mySQL, and the dead phone line. I'll leave this here in case anyone else runs into the problem.

**Comment by PepperKev** [comment]
I would like to mark this as resolved, but I don't know the process. If anyone can do that for me, I'd appreciate it!
