### ISSUE TITLE
MySql peventing Installer from running

### ISSUE THREAD

**Issue by codydaig** [twilio/OpenVBX#411]
I'm trying to install OpenVBX and the first step that checks the server is preventing the install from continuing because mysql isn't installed. MySql is not installed on the server, it lives on a separate server. So, how can I continue through the installation without mysql being installed?

Additional Information:
I'm installing this on a Dreamhost Shared Hosting Server and the mysql servers are separate from the php servers.

Thanks!

**Comment by ahmed-sigmalux** [comment]
I worked around this by proxying port 3306 from localhost to an external MySQL server. After you get past the installation check, you can change the MySQL host to any external IP.

**Comment by codydaig** [comment]
It was the PHP version. I was running PHP version 7 and the status page said good to go, but in reality that was the issue.

**Comment by navinkr91556** [comment]
Normal web server are using Cpanel and Cpanel use MariaDB on the server. 
The MariaDB is highly compatible with MySQL. The applications OpenVbx which require MySQL, not MariaDB. If you want to use it then go on cloud and install manually Apache, MySQL. 

For more information on how to install OpenVbx on cloud check out this link:- [Install OpenVbx](https://medium.com/@sinxloud/setup-and-install-openvbx-on-cloud-integrate-twilio-client-sinxloud-c500e5b78484)
